third set of task
js-tasks-ru/js-20210615_haharinru pull request #2
Opened 2021-06-25 12:18 UTC by Haharin

will be updated on the implementation

2021-06-25 12:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-25 12:49 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-25 13:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-25 13:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-25 13:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-25 16:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let props = path.split(`.`);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-06-25 16:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let props = path.split(`.`);
проверьте, а точно `let`?

2021-06-25 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      return undefined;
мы не возвращаем `undefined` вручную, достаточно просто `return`

2021-06-25 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
просто `return`

2021-06-25 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  console.log(pairs);
не оставляйте отладочные `console` в коде

2021-06-25 16:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    [pair[1]]: (obj[pair[1]] = pair[0]),
таких конструкций следует избегать в реальных проектах - они очень сложно читаются

2021-06-25 16:23 UTC, dosandk requested changes
решение `createGetter` необходимо поправить

2021-07-12 21:53 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-07-12 23:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-12 23:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-07-12 23:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-07-13 02:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-07-13 14:50 UTC, dosandk approved these changes
good 👍

2021-07-13 14:50 UTC, merged